name: Actualizar M3U8 Blada TV

on:
  workflow_dispatch:

  schedule:
    - cron: '*/30 * * * *'

jobs:
  actualizar:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Instalar Chromium
        run: npx playwright install chromium

      - name: Buscar M3U8
        run: node scripts/actualizar_m3u8.js

      - name: Guardar cambios
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add canales_m3u8.json partidos.json

          git commit -m "Actualizar enlaces M3U8" || echo "Sin cambios"

          git push
